#!/data/data/com.termux/files/usr/bin/sh

# 清除残留进程，打开显示
killall -9 termux-x11 2> /dev/null
termux-x11 :0 -dpi 96 &
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity

# 如果不是 root, 使用 su -c 重新执行脚本自身
if [ "$(id -u)" -ne 0 ]; then
    # shellcheck disable=SC2016
    exec su -c 'exec "$0" "$@"' "$0" "$@"
fi

# Chroot 路径
ChrootPath="/data/local/tmp/arch"

# 调用挂载脚本
/data/user/0/com.termux/files/home/.local/bin/arch-mount

# 等 X11 socket 就绪
XSocket="/data/data/com.termux/files/usr/tmp/.X11-unix/X0"
while [ ! -S "$XSocket" ]; do sleep 0.2; done

# 伪造 systemctl 和电源管理器
echo "#!/bin/sh
case \$1 in import-environment|list-jobs|start|stop|is-active|is-enabled) exit 0;; *) exec systemctl.orig \\\"\$@\\\" 2>/dev/null || exit 0;; esac" \
    > $ChrootPath/usr/bin/systemctl && chmod 755 $ChrootPath/usr/bin/systemctl
ln -sf /bin/true $ChrootPath/usr/bin/pm-is-supported

# Chroot 进入并启动桌面
exec chroot "$ChrootPath" /bin/su - yumeka -c "
mkdir -p /tmp/xdg-yumeka
chmod 0700 /tmp/xdg-yumeka
export DISPLAY=:0

# dbus-run-session startxfce4
dbus-launch --exit-with-session && TU_DEBUG=noconform ZINK_DESCRIPTORS=lazy ZINK_DEBUG=compact startxfce4
"
